### PR TITLE
WIP: Enable documentation.

### PR DESCRIPTION
**Pull request by Ismael-VC**
@swadey you only need to create an account at:
- https://readthedocs.org

Sync your repositories and enable this repo, be sure to select julia among the availble languages and Mkdocs markdown among the documentation alternatives.

Please let me know if you have any problem, I'll be expanding the examples here, thanks!

### CODE REVIEW

**Comment by Ismael-VC** [comment]
Example result from my fork:
- http://testlispsyntaxjl.readthedocs.org/en/latest

You can also add taggs and such

**Comment by Ismael-VC** [comment]
By the way we can use `[ci skip]` in the body of a commit or PR in order to avoid running tests for documentation related changes.

**Comment by Ismael-VC** [comment]
@swadey oh damn I closed this by accident! :sob:

**Comment by Ismael-VC** [comment]
Oh there it is again :wink:

**Comment by Ismael-VC** [comment]
I can squash the commits if you want. I'll keep adding more examples.

**Comment by swadey** [comment]
Dude this is cool.  Thanks for putting so much effort into starting these docs.  Merging.

**Comment by Ismael-VC** [comment]
@swadey I think you still have to register in readthedocs and add this repo to the automatic build process, currently what would be the default site (if you don't cahnge the title) doesn't exist yet:
- http://lispsyntaxjl.readthedocs.org/en/latest

This page is from my test from my repo:
- http://testlispsyntaxjl.readthedocs.org/en/latest

I used `testlispsyntaxjl` in order to have available the `lispsyntaxjl` name.

**Comment by swadey** [comment]
take a look

**Comment by Ismael-VC** [comment]
It seems to be expecting Rest doc files, I think markdown is easier:

> Please create a /home/docs/checkouts/readthedocs.org/user_builds/lispsyntaxjl/checkouts/latest/doc/index.rst or /home/docs/checkouts/readthedocs.org/user_builds/lispsyntaxjl/checkouts/latest/doc/README.rst file with your own content.

I could change the doc/index.md file to rst instead if you like. If you want to use the index.md file as is, you just have to confgure the project like this:



After that you should see the same result as in my test page, and every time a commit is merged readthedocs will auto generate and update the documentation website for us!

**Pull request merged**
